services:
  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: requirements/mariadb
    networks:
      - database
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 1s

  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wordpress
      - database
      - redis
    volumes:
      - wordpress:/var/www/html
      - adminer:/adminer
    env_file:
      - .env
  
  nginx:
    container_name: nginx
    restart: always
    build:
      context: requirements/nginx
    depends_on:
      - wordpress
      - adminer
    networks:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - adminer:/adminer
    ports:
      - 443:443

  redis:
    container_name: redis
    restart: always
    build:
      context: requirements/bonus/redis
    networks:
      - redis
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 1s
  
  adminer:
    container_name: adminer
    build:
      context: requirements/bonus/adminer
    networks:
      - wordpress
    volumes:
      - adminer:/adminer

  ftp:
    container_name: ftp
    restart: always
    build:
      context: requirements/bonus/ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress:/wordpress
    ports:
      - 21:21
    env_file:
      - .env
    

networks:
  wordpress:
  database:
  redis:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/gbaumgar/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/gbaumgar/data/wp
      o: bind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/gbaumgar/data/adminer
      o: bind