services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - database
    volumes:
      - database:/var/lib/mysql
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 1s

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: requirements/wordpress
    networks:
      - wordpress
      - database
      - redis
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - .env
  
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
    networks:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    restart: always

  redis:
    container_name: redis
    build:
      context: requirements/bonus/redis
    networks:
      - redis
    # volumes:
    #   - wordpress:/var/www/html
    # ports:
    #   - 443:443
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 1s

networks:
  wordpress:
  database:
  redis:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/gbaumgar/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/gbaumgar/data/wp
      o: bind