FROM debian:buster

# RUN \
# 	apt-get update \
# 	&& apt-get install -y redis-server 

# COPY --chown=redis conf/redis.conf /etc/redis/redis.conf

# CMD ["redis-server", "/etc/redis/redis.conf"]

# EXPOSE 6379